### PR TITLE
Exercise 9

### PR DESCRIPTION
**Pull request by hennigk**

### CODE REVIEW

**Comment by ziad-saab** [comment]
@hennigk unfortunately you can't do this exercise the way you did it. Your SQL logic is flawed, because IDs are not always going to be sequential. In a real system, rows might get deleted, and IDs can become quite erratic.

In this case you have to use the `LIMIT` part of an SQL query, specifically the part that uses two values, one for the number of results and one for the offset.

Can you please re-do that part of the exercise?

**Comment by hennigk** [comment]
I instead created an array of all of the ordered ids. this way I can pull out the id's from the array that are in the ten positions I want and display the results for the id's i retrieved from the array. 
I figured I would have less code to rewrite.

**Comment by ziad-saab** [comment]
@hennigk this is still not ideal unfortunately, for many reasons:
1. In a real-world app, there could be thousands upon thousands of IDs. Maintaining that into an array can become a problem, one that can easily be avoided with my suggestion.
2. As you are creating your list of IDs, don't forget that in a real-world scenario you are not the only person using the system! Many interactions can be removing/adding entries to the database, and your list of IDs will never be up to date with the real data.

This is why the best way to do this is to use `LIMIT` and `OFFSET`.

**Comment by ziad-saab** [comment]
:+1:

**Pull request closed without merging**
