### PR TITLE
Exercise 10: Getting some data in MySQL!

### PR DESCRIPTION
**Pull request by karlysun**

### CODE REVIEW

**Comment by ziad-saab** [comment]
@karlysun unfortunately, even though it seems to be working right now, you can't issue the two queries right next to each other. you have no guarantee that the first request will be completed when doing the second request. since they are asynchronous operations, you have to do them in continuation!

**Comment by karlysun** [comment]
Updated.

**Comment by ziad-saab** [comment]
@karlysun awesome! Now that you know how this stuff works, I'd like to point out that, when you make an `INSERT` request with the `node-mysql` library, it will already return you the inserted ID in `result.insertId`. Try it out :)

**Comment by karlysun** [comment]
I tried with `result.insertId`, `result[0].insertId` & `result[0][0].insertId`. It doesn't seem to be working.

**Comment by karlysun** [comment]
Updated with all console.log

**Comment by karlysun** [comment]
Updated

**Comment by ziad-saab** [comment]
@karlysun :+1:

**Pull request closed without merging**
