### PR TITLE
Exercise 9: Pagination

### PR DESCRIPTION
**Pull request by Cathe313**

### CODE REVIEW

**Comment by ziad-saab** [comment]
@Cathe313 you cannot do `WHERE ID BETWEEN...`. You never know the distribution of IDs. The only way to get this done properly is to use `LIMIT` with `OFFSET`.

Please check the MySQL documentation for `SELECT` to get a working example using limits and offsets, and re-do that part of the exercise when you have some time.

**Comment by Cathe313** [comment]
Thanks for the feedback, I did as suggested.

**Comment by ziad-saab** [comment]
@Cathe313 amazing!!! One last thingy. Your global `count` variable is being shadowed by the `count` parameter in your main function. You don't actually need the global variable. Can you fix this?

**Comment by Cathe313** [comment]
Good point! It does work without it...

**Comment by ziad-saab** [comment]
@Cathe313 :+1:  :+1:  :+1:  :+1:  :+1:  :+1:  :+1:

**Pull request closed without merging**
